site_name: EOEPCA Resource Registration Building Block
site_url: https://eoepca.readthedocs.io/projects/resource-registration/en/latest/
repo_url: https://github.com/EOEPCA/resource-registration/
edit_uri: "edit/main/docs/"

nav:
  - EOEPCA Documentation: https://eoepca.readthedocs.io/
  - Resource Registration:
    - index.md
    - Getting Started:
      - getting-started/quick-start.md
    - Design:
      - Architecture: design/overview.md
      - Components:
        - Registration API: design/registration-api-design.md
        - Harvester: design/harvester-design.md
#        - eodm: https://geopython.github.io/eodm/
#        - pygeoapi: https://docs.pygeoapi.io
    - Usage:
      - Registration API: user-guide/registration-api-usage.md
      - Harvester Tutorial: 
        - Introduction: user-guide/harvester-tutorial-intro.md
        - 1. BPMN Design: user-guide/harvester-tutorial-part1.md
        - 2. Worker implementation: user-guide/harvester-tutorial-part2.md
        - 3. Deployment and execution: user-guide/harvester-tutorial-part3.md
#    - Administration:
#      - admin/configuration.md
#      - admin/maintenance.md
    - API:
      - Registration API: api-specification/registration-api-specification.md
      - Harvester: api-specification/harvester-api-specification.md

theme:
  name: material # https://squidfunk.github.io/mkdocs-material/creating-your-site/
  navigation_depth: 4

  # For `material` theme...
  logo: img/favicon.ico
  favicon: img/favicon.ico
  features:
#    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.edit
    - search.highlight
    - toc.follow

extra_css:
  - css/eoepca.css

plugins:
  - autorefs
  - glightbox
  - search  
  - swagger-ui-tag
  # - pub-debugger:
  #     console_log:
  #       enabled: true
  #       log_level: INFO
  #     file_log:
  #       enabled: false
  #     zip_log:
  #       enabled: false

markdown_extensions:
  - tables
  - toc:
      permalink: ⚓︎
      toc_depth: 4
  - smarty
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
