name: 'Fetch and Initialize'
description: 'Fetches and initializes the repository, then sets up Python.'


# define inputs from workflow
inputs:
  repository:
    description: 'The repository to check out'
    required: true
  dependency:
    description: 'The tool to use'
    required: true
  cmd_run:
    description: 'cmd'
    required: true
  opt_in:
    description: "Black toml"
    required: false
    default: ""



runs:

  using: 'composite'

  steps:

    # first step: fetch the project data that is to be checked
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          lib/
          .github
          ${{ inputs.opt_in }}
        sparse-checkout-cone-mode: false

    # second step: install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    # third step: install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ${{ inputs.dependency }}
      shell: bash

    # fourth step: run the tool on given project code
    - name: Tool Run
      run: |
        ${{ inputs.cmd_run }}
      shell: bash

