# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Common Library CI

# push und pull paths and/or files set here are only the ones triggering this workflow. The actual code to be checked is
# set via sparsecheckout in the step "Checkout Repository".
on:
  push:
    branches:
      - "main"
    paths:
      - 'lib/**'
      - '.github/workflows/common-library-ci.yml'


  pull_request:
    branches:
      - "main"
    paths:
      - 'lib/**'
      - '.github/workflows/common-library-ci.yml'



permissions:
 contents: read

jobs:
  black-Formatting:

    runs-on: ubuntu-latest

    steps:

      # alternativ zu "use : actions / checkout@v4" sparse checkout für ausgewählte Daten
    - name: Checkout Repository
      run: |
        git init
        git remote add origin https://github.com/${{ github.repository }}.git
        git config core.sparseCheckout true
        
        echo "lib/" >> .git/info/sparse-checkout
        
        git pull origin main
  

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black


    - name: Format check with black
      run: black --check --diff --color .



  flake8-Linting:

    runs-on: ubuntu-latest

    steps:

      # alternativ zu "use : actions / checkout@v4" sparse checkout für ausgewählte Daten
      - name: Checkout Repository
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git config core.sparseCheckout true

          echo "lib/" >> .git/info/sparse-checkout

          git pull origin main


      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8


      - name: Lint with flake8
        run: |
          flake8 --max-line-length 120 --count --statistics .



  pytest-Testing:

    runs-on: ubuntu-latest

    steps:

      # alternativ zu "use : actions / checkout@v4" sparse checkout für ausgewählte Daten
      - name: Checkout Repository
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git config core.sparseCheckout true
          
          echo "lib/" >> .git/info/sparse-checkout
          
          git pull origin main


      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          

      - name: Test with pytest
        run: |
          pytest

